language: objective-c
osx_image: xcode611
xcode_project: AeroGearHttpStub.xcodeproj
xcode_scheme: AeroGearHttpStub
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
